In [16]:
import sys
##sys.path.append('c:\\users\\sakurai.masaru.ncs\\appdata\\local\\programs\\python\\python312\\lib\\site-packages')
print(sys.executable)
##print(sys.path)
import numpy as np
##import panda as pd

##ハイパーパラメータの設定 今回はガンマとアルファ
gamma = 0.75
alpha = 0.9

#工場の中の場所と状態を表している。Aの場所が０という状態
location_to_state = {'A':0,
                     'B':1,
                     'C':2,
                     'D':3,
                     'E':4,
                     'F':5,
                     'G':6,
                     'H':7,
                     'I':8,
                     'J':9,
                     'K':10,
                     'L':11,

}

#アクション＝行動を定義
actions = [0,1,2,3,4,5,7,8,9,10,11]

#報酬を定義　A-Bに移動したときに得られる報酬あれば１、A-Eに行けなければ、報酬は0
              #A B C D E F G H I J K L  <-TOのイメージ
R = np.array([
              [0,1,0,0,0,0,0,0,0,0,0,0],#Aから移動できる場所への報酬　Bにしか移動できないので2個目だけ1
              [1,0,1,0,0,1,0,0,0,0,0,0],
              [0,1,0,0,0,0,1,0,0,0,0,0],
              [0,0,0,0,0,0,0,1,0,0,0,0],
              [0,0,0,0,0,0,0,0,1,0,0,0],
              [0,1,0,0,0,0,0,0,0,1,0,0],
              [0,0,1,0,0,0,1,1,0,0,0,0],
              [0,0,0,100,0,0,1,0,0,0,0,1],
              [0,0,0,0,1,0,0,0,0,1,0,0],
              [0,0,0,0,0,1,0,0,1,0,1,0],
              [0,0,0,0,0,0,0,0,0,1,0,1],
              [0,0,0,0,0,0,0,1,0,0,1,0]])

#Q値の設定　いったん初期状態
Q = np.array(np.zeros([12,12])) 
print(R)
print(Q)

c:\Users\sakurai.masaru.NCS\AppData\Local\Programs\Python\Python312\python.exe
[[  0   1   0   0   0   0   0   0   0   0   0   0]
 [  1   0   1   0   0   1   0   0   0   0   0   0]
 [  0   1   0   0   0   0   1   0   0   0   0   0]
 [  0   0   0   0   0   0   0   1   0   0   0   0]
 [  0   0   0   0   0   0   0   0   1   0   0   0]
 [  0   1   0   0   0   0   0   0   0   1   0   0]
 [  0   0   1   0   0   0   1   1   0   0   0   0]
 [  0   0   0 100   0   0   1   0   0   0   0   1]
 [  0   0   0   0   1   0   0   0   0   1   0   0]
 [  0   0   0   0   0   1   0   0   1   0   1   0]
 [  0   0   0   0   0   0   0   0   0   1   0   1]
 [  0   0   0   0   0   0   0   1   0   0   1   0]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 

In [17]:

for i in range(1000):
    #初期値を設定。0-12までのランダム値
    current_state = np.random.randint(0,12)
    #次にとることのできる状態(場所)を取得　報酬の配列を使う
    playable_actions = []
    for j in range(12):
        if R[current_state,j] > 0 :
            playable_actions.append(j)
    #次の状態
    next_state = np.random.choice(playable_actions) #次のアクションをランダムにとる

    #temp defference を求めてQ値を更新する。
    TD = R[current_state,next_state] + gamma * Q[next_state,np.argmax(Q[next_state,])]-Q[current_state,next_state]
    Q[current_state,next_state] = Q[current_state,next_state]+ alpha*TD

#print(Q)

#場所と状態を示す変数を作る
state_to_location = {state : location for location,state in location_to_state.items()}

print(state_to_location)
    



{0: 'A', 1: 'B', 2: 'C', 3: 'D', 4: 'E', 5: 'F', 6: 'G', 7: 'H', 8: 'I', 9: 'J', 10: 'K', 11: 'L'}


In [18]:
def route(starting_location, ending_location):
    route = [starting_location]
    next_location = starting_location
    while(next_location != ending_location):#ゴールを決める。次の状態がゴールでない限り続ける
        starting_state = location_to_state[starting_location] #ここでのstatingはpre　次の状態をとる前の状態と思う
        next_state = np.argmax(Q[starting_state,])
        next_location = state_to_location[next_state]
        route.append(next_location)
        starting_location = next_location
        print(next_location)
    return route

print(route('A','D'))


B
C
G
H
D
['A', 'B', 'C', 'G', 'H', 'D']
